# Data preprocessing

In [1]:
#import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#load data set
data_set = pd.read_csv("E:\\sign language\\sign_mnist_test.csv")

In [3]:
data_set.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      6     149     149     150     150     150     151     151     150   
1      5     126     128     131     132     133     134     135     135   
2     10      85      88      92      96     105     123     135     143   
3      0     203     205     207     206     207     209     210     209   
4      3     188     191     193     195     199     201     202     203   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0     151  ...       138       148       127        89        82        96   
1     136  ...        47       104       194       183       186       184   
2     147  ...        68       166       242       227       230       227   
3     210  ...       154       248       247       248       253       236   
4     203  ...        26        40        64        48        29        46   

   pixel781  pixel782  pixel783  pixel784  
0       106       112       120       107  
1       184       184       182       180  
2       226       225       224       222  
3       230       240       253       255  
4        49        46        46        53  

[5 rows x 785 columns]

In [23]:
#seperating dependent and independent variables
x = data_set.iloc[:,1:].values
y = data_set.iloc[:,0].values

In [28]:
x.shape

(7172, 784)

In [29]:
y.shape

(7172,)

In [27]:
x

array([[149, 149, 150, ..., 112, 120, 107],
       [126, 128, 131, ..., 184, 182, 180],
       [ 85,  88,  92, ..., 225, 224, 222],
       ...,
       [190, 191, 190, ..., 211, 209, 208],
       [201, 205, 208, ...,  67,  70,  63],
       [173, 174, 173, ..., 195, 193, 192]], dtype=int64)

In [30]:
y

array([ 6,  5, 10, ...,  2,  4,  2], dtype=int64)

In [31]:
# split the dataset into train and test 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 0)

In [32]:
x_train

array([[110, 120, 127, ...,  38,  71,  54],
       [ 86,  95, 109, ..., 192, 193, 193],
       [146, 146, 146, ..., 174, 172, 172],
       ...,
       [118, 120, 124, ...,  29,  50,  35],
       [139, 142, 144, ..., 176, 173, 166],
       [186, 186, 187, ..., 211, 209, 202]], dtype=int64)

In [33]:
x_train.shape

(5379, 784)

In [34]:
x_test.shape

(1793, 784)

In [39]:
# feature scaling
from sklearn.preprocessing import StandardScaler
st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.fit_transform(x_test)

In [40]:
x_train

array([[-0.84449726, -0.70670112, -0.6314699 , ..., -1.81031704,
        -1.26961276, -1.46611515],
       [-1.39527916, -1.30261294, -1.07629397, ...,  0.5286022 ,
         0.55044565,  0.57126221],
       [-0.01832441, -0.08695283, -0.16193338, ...,  0.25522203,
         0.23715691,  0.263457  ],
       ...,
       [-0.66090329, -0.70670112, -0.70560724, ..., -1.94700713,
        -1.5829015 , -1.74460557],
       [-0.17896913, -0.18229872, -0.21135828, ...,  0.2855976 ,
         0.25207542,  0.17551265],
       [ 0.89964542,  0.86650608,  0.851277  , ...,  0.81717015,
         0.78914183,  0.70317873]])

# Fitting the SVM classifier to the training dataset

In [42]:
from sklearn.svm import SVC # support vector classifier
classifier = SVC(kernel = 'sigmoid',random_state = 0)
classifier.fit(x_train,y_train)

SVC(kernel='sigmoid', random_state=0)

In [43]:
# Predict the test set result
y_pred = classifier.predict(x_test)

In [44]:
y_pred

array([13,  6, 15, ..., 23,  0, 14], dtype=int64)

In [45]:
y_test

array([13,  6, 19, ..., 23,  0,  5], dtype=int64)

In [53]:
# creating the confusion matrix
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test,y_pred)

In [56]:
cm

array([[84,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,
         0,  0,  0,  0,  0,  1,  0,  0],
       [ 0, 69,  1,  2,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0, 16,  2,
         0,  0,  0,  0,  0,  0,  6,  1],
       [ 0,  0, 70,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  6,  3,  1,
         0,  0,  0,  0,  0,  0,  7,  0],
       [ 0,  8,  0, 24,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  8,  0,
         0,  0,  1,  6,  2,  0, 11,  4],
       [ 2,  0,  1,  0, 88,  0,  1,  0,  0,  0,  0,  4,  4,  0,  5,  1,
         0,  0,  0,  0,  0,  0,  7,  0],
       [ 0,  2,  3,  0,  0, 30,  0,  1,  0, 15,  0,  0,  0,  4,  4,  0,
         0,  0,  0,  0,  0,  0,  4,  1],
       [ 0,  0,  0,  4,  0,  2, 35, 21,  1,  4,  0,  1,  0,  0,  5,  6,
         0,  0,  2,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0, 28, 69,  0,  1,  1,  0,  1,  0, 11,  6,
         0,  0,  1,  0,  0,  3,  3,  1],
       [ 0,  0,  0,  2,  0,  0,  0,  0, 37,  4,  0,  1,  1,  0,  9,  2,
         0,  1,  0,  1, 